[TA-3481]: Add ownable interface to erc20 precompile
xrplevm/evmos pull request #8
Opened 2024-10-29 15:13 UTC by GuillemGarciaDev

# [TA-3481]: Add ownable interface to erc20 precompile

# Description

This PR aims to implement the `Ownable` openzeppelin contract interface for erc20 precompile.
It includes a migration to migrate the `TokenPair` type with the new field `ContractOwnerAddress`.

---

## Author Checklist

**All** items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.

I have...

- [ ] tackled an existing issue or discussed with a team member
- [ ] left instructions on how to review the changes
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/evmos/evmos/blob/main/CONTRIBUTING.md#pr-targeting))

## Reviewers Checklist

**All** items are required.
Please add a note if the item is not applicable
and please add your handle next to the items reviewed
if you only reviewed selected items.

I have...

- [ ] added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] confirmed all author checklist items have been addressed
- [ ] confirmed that this PR does not change production code
- [ ] reviewed content
- [ ] tested instructions (if applicable)
- [ ] confirmed all CI checks have passed

2024-10-30 10:31 UTC, AdriaCarrera requested changes

2024-10-30 10:31 UTC, AdriaCarrera commented on proto/evmos/erc20/v1/erc20.proto
> +  string contract_owner_address = 5;
Això hauria de ser nullable

2024-10-30 10:31 UTC, AdriaCarrera commented on app/upgrades/v19/upgrades.go
> +	pair := erc20types.NewTokenPair(wrappedContractAddr, nativeDenom, erc20types.OWNER_MODULE, "")
Aquesta funció no s'hauria de modificar en cap cas ja que la upgrade ja està feta

2024-10-30 10:31 UTC, AdriaCarrera commented on x/erc20/types/token_pair.go
> +func NewTokenPair(erc20Address common.Address, denom string, contractOwner Owner, contractOwnerAddr string) TokenPair {
Si posem contractOwnerAdddress com a nil, podem evitar canviar la firma d'aquesta funció i modificar tants fitxers

2024-10-30 10:31 UTC, AdriaCarrera commented on proto/evmos/erc20/v1/erc20.proto
> +  string contract_owner_address = 5;
Cambiar el nom a `owner_address`

2024-10-30 10:31 UTC, AdriaCarrera commented on precompiles/erc20/erc20.go
> +	GasMint              = 3_000_000
Comprovar quins son els valors reals

2024-10-30 10:31 UTC, AdriaCarrera commented on precompiles/erc20/erc20.go
> +	storeKey       storetypes.StoreKey
Posar el Erc20Keeper aquí

2024-10-30 10:31 UTC, AdriaCarrera commented on precompiles/erc20/tx.go
> +	newOwner, err := ParseTransferOwnershipArgs(args)
Moure la llogica al Erc20Keeper

2024-11-04 10:50 UTC, AdriaCarrera requested changes

2024-11-04 10:50 UTC, AdriaCarrera commented on precompiles/erc20/errors.go
> +	case strings.Contains(err.Error(), "ERC20: unauthorized") || strings.Contains(err.Error(), "authorization not found"):
Per que aquest tenen el prefix `ERC20:` ?

2024-11-04 10:50 UTC, AdriaCarrera commented on precompiles/erc20/interfaces.go
> +	GetTokenPairOwnerAddress(ctx sdk.Context, token string) (sdk.AccAddress, error)
No seria millor passar-li tot el `TokenPair` enlloc de un string?

2024-11-04 10:50 UTC, AdriaCarrera commented on precompiles/erc20/interfaces.go
> +	TransferOwnership(ctx sdk.Context, sender, newOwner sdk.AccAddress, token string) error
Ídem

2024-11-04 10:50 UTC, AdriaCarrera commented on precompiles/erc20/query.go
> +	p.tokenPair.SetOwnerAddress(ownerAddr.String())
Per que es fa un `SetOwnerAddress` aquí?

2024-11-04 10:50 UTC, AdriaCarrera commented on precompiles/erc20/tx.go
> +	err = p.erc20Keeper.MintCoins(ctx, minter, toAddr, math.NewIntFromBigInt(amount), p.tokenPair.GetERC20Contract().Hex())
No sería millor passar-li tot el `TokenPair` enlloc de `GetERC20Contract`?

2024-11-04 10:50 UTC, AdriaCarrera commented on precompiles/erc20/tx.go
> +	err = p.erc20Keeper.BurnCoins(ctx, burner, math.NewIntFromBigInt(amount), p.tokenPair.GetERC20Contract().Hex())
Ídem

2024-11-04 10:50 UTC, AdriaCarrera commented on precompiles/erc20/tx.go
> +	err = p.erc20Keeper.TransferOwnership(ctx, sender, sdk.AccAddress(newOwner.Bytes()), p.tokenPair.GetERC20Contract().Hex())
Ídem

2024-11-04 10:50 UTC, AdriaCarrera commented on precompiles/erc20/tx_test.go
> +			"execution reverted",
Aquest error es poc descriptiu, no?

2024-11-04 10:50 UTC, AdriaCarrera commented on precompiles/erc20/tx_test.go
> +				// owner, err := precompile.GetContractOwnerAddress(s.network.GetContext())
Borrar comments

2024-11-04 10:50 UTC, AdriaCarrera commented on proto/evmos/erc20/v1/erc20.proto
> +  // contract_owner_address is the address of the current owner of the token
Fix comment `contract_owner_address` és el nom antic

2024-11-04 10:50 UTC, AdriaCarrera commented on proto/evmos/erc20/v1/tx.proto
> +  string contract_address = 1;
Aquest no hauria de tenir el type address? `(cosmos_proto.scalar) = "cosmos.AddressString"`

2024-11-04 10:50 UTC, AdriaCarrera commented on proto/evmos/erc20/v1/tx.proto
> +  // to is the address to mint the tokens to
Ídem

2024-11-04 10:50 UTC, AdriaCarrera commented on proto/evmos/erc20/v1/tx.proto
> +  string contract_address = 1;
Ídem

2024-11-04 10:50 UTC, AdriaCarrera commented on proto/evmos/erc20/v1/tx.proto
> +  string sender = 3;
Ídem

2024-11-04 10:50 UTC, AdriaCarrera commented on x/erc20/keeper/erc20.go
> +	if k.bankKeeper.BlockedAddr(receiver.Bytes()) {
I aquesta assertion? Aplica també al transfer?

2024-11-04 10:50 UTC, AdriaCarrera commented on x/erc20/keeper/erc20.go
> +	// if p.tokenPair.Denom == utils.BaseDenom {
Borrar comments

2024-11-04 10:50 UTC, AdriaCarrera commented on x/erc20/keeper/token_pairs.go
> +	tokenPairID := k.GetERC20Map(ctx, common.HexToAddress(token))
No és pot fer més eficient aquesta busqueda?

2024-11-04 10:50 UTC, AdriaCarrera commented on x/erc20/keeper/token_pairs.go
> +	key := pair.GetID()
No es pot aprofitar el `SetTokenPair` ?

2024-11-04 10:50 UTC, AdriaCarrera commented on x/erc20/types/token_pair_test.go
> +		{msg: "Register token pair - invalid address (no hex)", pair: types.TokenPair{"0x5dCA2483280D9727c80b5518faC4556617fb19ZZ", "test", true, types.OWNER_MODULE, ""}, expectPass: false},
Treure el `""` ja que per default es queda buit

2024-11-04 11:02 UTC, GuillemGarciaDev commented on x/erc20/types/token_pair_test.go
> +		{msg: "Register token pair - invalid address (no hex)", pair: types.TokenPair{"0x5dCA2483280D9727c80b5518faC4556617fb19ZZ", "test", true, types.OWNER_MODULE, ""}, expectPass: false},
Si s'inicialitza un struct sense les labels dels fields s'han d'especificar tots els camps

2024-11-04 13:58 UTC, merged